// =============================================================================
// Gan Family Tree — Data
// =============================================================================
// This is the only file you need to edit to update the family tree.
//
// PEOPLE: one entry per person.
//   id         unique slug, referenced by unions (required)
//   name       display name (required)
//   gender     "M" | "F" | null
//   born       birth year or full date string, e.g. 1950 or "1950-03-14"; null if unknown
//   died       death year/date, or null if living/unknown
//   birthPlace where they were born
//   location   where they live now
//   occupation what they do / did
//   notes      free text shown on their page
//   chineseName  Chinese name as recorded in the clan genealogy, e.g. "颜华胜"
//   photo      optional path to a picture, e.g. "photos/victor.jpg"
//              (drop image files into a photos/ folder in this repo)
//   unknown    true = placeholder person whose identity isn't known yet
//
// UNIONS: one entry per couple (marriage, partnership, or past relationship).
//   partners   [idA, idB]
//   status     "married" | "divorced" | "separated" | "partner" | "widowed"
//   start,end  years, or null
//   children   array of person ids born to this couple
//
// Parents, siblings (including half-siblings), and children are all derived
// from UNIONS automatically — never listed twice.
// =============================================================================

const PEOPLE = [

  // --------------------------------------------------------------------------
  // Dad's side — the patriline from the clan genealogy (顏氏家谱, the Yongchun
  // 仁贵 family, 赐美堂 hall): 亨晓 (30th gen) → 利潘 (31st) → 贞录 (32nd) →
  // 文雾/Gan Yong Teng (33rd)
  // --------------------------------------------------------------------------
  {
    id: "gan-30-hengxiao",
    name: "顏亨曉 (仁山公)",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: "Yongchun, Fujian, China", location: null, occupation: null,
    notes: "30th generation, honorific 仁山公 — sixth son of 元初 (29th). Father of six 利-generation sons: 利鸟 (明德公, settled Malaya/Singapore), 利鉴 (died young), 利琴 (达德公, remained in Yongchun), 利成 (died young), 利潘 (曲谭公, our line, settled Malaya/Singapore), and 利恩 (俭德公, settled Malaya/Singapore).",
    unknown: false,
  },
  {
    id: "gan-30-hengxiao-wife",
    name: "Wife of 顏亨曉",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Name not yet transcribed from the genealogy.",
    unknown: true,
  },
  {
    id: "gan-31-lipan",
    name: "顏利潘 (曲谭公)",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: "Yongchun, Fujian, China", location: null, occupation: null,
    notes: "31st generation, honorific 曲谭公 — fifth of 亨曉 仁山公's six sons; emigrated and settled in Malaya/Singapore. Father of the five 貞-generation brothers; the genealogy section covering this whole branch is headed 利潘公 (pages 16–23).",
    unknown: false,
  },
  {
    id: "gan-31-lipan-wife",
    name: "Wife of 顏利潘",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Name not yet transcribed from the genealogy.",
    unknown: true,
  },
  {
    id: "yan-zhengai",
    name: "顏貞溉",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "32nd generation — eldest of 利潘's five sons. His sons 文炭, 文榜, 文垤, 文博, and 文棣 and their families fill genealogy pages 16–20 (households in Kuala Lumpur and Klang), including 顏章本, the register's corrections coordinator.",
    unknown: false,
  },
  {
    id: "yan-zhenzan",
    name: "顏貞贊",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "32nd generation — second of 利潘's five sons, of Kuala Lumpur. Sons 文禁, 嘉炳, and 嘉添 (page 21); most of their descendants are marked unknown in the register.",
    unknown: false,
  },
  {
    id: "yan-zhenli",
    name: "顏貞立",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "32nd generation — third of 利潘's five sons, of Kuala Lumpur. Son 吉宁 (page 21); descendants marked unknown in the register.",
    unknown: false,
  },
  {
    id: "gg-gan-father",
    name: "顏貞錄",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Victor's great-grandfather, 32nd generation — fourth of the 贞-generation brothers (贞溉, 贞赞, 贞立, 贞录, 贞仍) in the 利潘公 branch. His family appears on pages 21–23 of the genealogy.",
    unknown: false,
  },
  {
    id: "yan-zhenreng",
    name: "顏貞仍",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "32nd generation — fifth of 利潘's five sons. Sons 文模, 文元, and 教丹 (page 23); their descendants are marked unknown in the register.",
    unknown: false,
  },
  {
    id: "gg-gan-mother",
    name: "Great-Grandmother Gan",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏貞錄's wife, Gan Yong Teng's mother. Name not yet transcribed — the elderly couple photographed on genealogy page 21 may be her and 貞錄.",
    unknown: true,
  },

  // --------------------------------------------------------------------------
  // 文啟's branch (genealogy pages 21–22) — the Penang / Sungai Petani cousins
  // --------------------------------------------------------------------------
  {
    id: "li-jintao",
    name: "李金桃",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏文啟's wife. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-zhangyi",
    name: "顏章仪",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏文啟 — 34th generation. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "chen-yue-e",
    name: "陈月娥",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏章仪's wife. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-huaen",
    name: "顏华恩",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏章仪. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "guo-fuyi",
    name: "郭富逸",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏华恩's wife. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-yuxiang",
    name: "顏宇翔",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏华恩 — 36th generation. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-xinyue",
    name: "顏欣玥",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏华恩. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-tingjuan",
    name: "顏婷娟",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏章仪. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "feng-jihao",
    name: "冯基豪",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏婷娟's husband. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "feng-yuheng",
    name: "冯昱恒",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏婷娟 and 冯基豪. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "feng-ruiheng",
    name: "冯睿恒",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏婷娟 and 冯基豪. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-huaqun",
    name: "顏华群",
    gender: null,
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Child of 顏章仪; spouse 杜锦聪. The register's formatting leaves the couple's roles ambiguous. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "du-jincong",
    name: "杜锦聪",
    gender: null,
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏华群's spouse. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-zhangxiang",
    name: "顏章祥",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: "Sungai Petani, Kedah, Malaysia", occupation: null,
    notes: "Son of 顏文啟 — 34th generation; his household settled in Sungai Petani, Kedah. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "li-suping",
    name: "李素萍",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏章祥's wife. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-huazhao",
    name: "顏华钊",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: "Sungai Petani, Kedah, Malaysia", occupation: null,
    notes: "Son of 顏章祥, of Sungai Petani. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "chen-siyi",
    name: "陈思贻",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏华钊's wife. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-yurui",
    name: "顏宇睿",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏华钊 — 36th generation. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-yuhui",
    name: "顏宇慧",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏华钊. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-huahan",
    name: "顏华翰",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: "Penang, Malaysia", occupation: null,
    notes: "Son of 顏章祥, of Penang. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "huang-meimei",
    name: "黄美美",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏华翰's wife. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-yujun36",
    name: "顏宇隽",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏华翰 — 36th generation. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-huawei",
    name: "顏华伟",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: "Penang, Malaysia", occupation: null,
    notes: "Son of 顏章祥, of Penang. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "wang-xiuqing",
    name: "王修晴",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏华伟's wife. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-yuxin",
    name: "顏宇信",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏华伟 — 36th generation. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-yuyi",
    name: "顏宇宜",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏华伟. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-zhangyao",
    name: "顏章耀",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏文啟 — 34th generation. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "li-yaxiang",
    name: "李亚香",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏章耀's wife. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-suzhu",
    name: "顏素珠",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏文啟. Per the genealogy, page 21.",
    unknown: false,
  },
  {
    id: "yan-suling",
    name: "顏素玲",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏文啟. Per the genealogy, page 22.",
    unknown: false,
  },
  {
    id: "peng-guoying",
    name: "彭国英",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏素玲's husband. Per the genealogy, page 22.",
    unknown: false,
  },

  // --------------------------------------------------------------------------
  // 文謹's, 文經's, and 文娥's families (genealogy page 23)
  // --------------------------------------------------------------------------
  {
    id: "lin-cuiqin",
    name: "林翠琴",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏文謹 and 林紀鴻 — Han Tiong Lim's sister. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "lan-quanrui",
    name: "蓝铨锐",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "林翠琴's husband. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "lan-renli",
    name: "蓝仁利",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 林翠琴 and 蓝铨锐. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "chen-zhuniang",
    name: "陳珠娘",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏文經's wife. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "yan-zhangcai",
    name: "顏章彩",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏文經 — 34th generation. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "lin-wenquan",
    name: "林文泉",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏章彩's husband. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "lin-shutong",
    name: "林舒统",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏章彩 and 林文泉. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "yan-zhangyan",
    name: "顏章燕",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏文經 — 34th generation. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "wang-shian",
    name: "王世安",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏章燕's husband. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "wang-jinchuan",
    name: "王进川",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏章燕 and 王世安. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "wang-jingfen",
    name: "王静芬",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏章燕 and 王世安. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "wang-jingling",
    name: "王静铃",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Daughter of 顏章燕 and 王世安. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "qiu-jinlin",
    name: "丘金粦",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏文娥's husband. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "qiu-cuiyue",
    name: "丘崔月",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Child of 顏文娥 and 丘金粦. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "qiu-zhuangming",
    name: "丘壮铭",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏文娥 and 丘金粦. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "qiu-zhuangrong",
    name: "丘壮荣",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏文娥 and 丘金粦. Per the genealogy, page 23.",
    unknown: false,
  },
  {
    id: "qiu-zhuangwei",
    name: "丘壮威",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Son of 顏文娥 and 丘金粦. Per the genealogy, page 23.",
    unknown: false,
  },

  // --------------------------------------------------------------------------
  // Dad's side — grandparents
  // --------------------------------------------------------------------------
  {
    id: "grandpa-gan",
    name: "Gan Yong Teng",
    gender: "M",
    chineseName: "顏文雾",
    born: null, died: null,
    birthPlace: null, location: "Kuala Lumpur, Malaysia", occupation: null,
    notes: "Victor's paternal grandfather. Known as Gan Boon Boo (文雾) before marriage — he appears under that name in the clan genealogy, second of 顏貞錄's six children (page 22). The genealogy marks his branch 吉隆坡 (Kuala Lumpur). Photo from the genealogy.",
    photo: "photos/gan-yong-teng.jpg",
    unknown: false,
  },
  {
    id: "grandma-gan",
    name: "Tan Seok Eng",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Victor's paternal grandmother, Gan Yong Teng's wife.",
    unknown: false,
  },

  // --------------------------------------------------------------------------
  // Dad's side — the eight Gan siblings, in birth order: Forest, an unknown
  // brother, Simon, another unknown brother, Cheong Koon, Eric, John,
  // Jacqueline
  // --------------------------------------------------------------------------
  {
    id: "forest-gan",
    name: "Forest Gan",
    gender: "M",
    chineseName: "顏章琳",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Victor's uncle — eldest of the eight Gan siblings. The genealogy (page 22) lists him as 章琳, unmarried (单身).",
    unknown: false,
  },
  {
    id: "gan-sibling-2",
    name: "顏章池",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Second-oldest of the eight Gan siblings; father of Tinie, Michael, and James. Chinese name from the genealogy (page 22); English name still unknown.",
    unknown: false,
  },
  {
    id: "gan-sibling-3",
    name: "顏章炫",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Fourth-oldest of the eight Gan siblings; father of Tivien and Alex. Chinese name from the genealogy (page 22); English name still unknown.",
    unknown: false,
  },
  {
    id: "cheong-koon-gan",
    name: "Cheong Koon Gan",
    gender: "M",
    born: 1950, died: null,
    birthPlace: null,
    location: "Mississauga, Ontario, Canada",
    occupation: null,
    chineseName: "顏章堃",
    notes: "Victor's dad. Fifth-oldest of the eight Gan siblings; 章堃 in the genealogy (page 22).",
    unknown: false,
  },
  {
    id: "eric-gan",
    name: "Eric Gan",
    gender: "M",
    born: "19XX", died: null,
    birthPlace: null,
    location: "Kuala Lumpur, Malaysia",
    occupation: null,
    chineseName: "顏章銮",
    notes: "Victor's uncle. Serene and Elaine's father. Sixth-oldest of the eight Gan siblings; 章銮 in the genealogy.",
    unknown: false,
  },
  {
    id: "simon-gan",
    name: "Simon Gan",
    gender: "M",
    born: "19XX", died: null,
    birthPlace: null,
    location: "Purmerend, Netherlands",
    occupation: null,
    chineseName: "顏章铨",
    notes: "Victor's uncle. Jonathan's father. Third-oldest of the eight Gan siblings; 章铨 in the genealogy, where he is also listed under his uncle 文喜 with the note 过房 (adopted across to that line).",
    unknown: false,
  },
  {
    id: "jacqueline-gan",
    name: "Jacqueline Gan",
    gender: "F",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    chineseName: "顏丽珠",
    notes: "Victor's aunt. Maria's mother. Youngest of the eight Gan siblings; 丽珠 in the genealogy.",
    unknown: false,
  },
  {
    id: "john-gan",
    name: "John Gan",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    chineseName: "顏章昕",
    notes: "Victor's uncle. Natalie and Stephanie's father. Seventh-oldest sibling and youngest Gan brother; 章昕 in the genealogy.",
    unknown: false,
  },

  // --------------------------------------------------------------------------
  // Lim branch — Gan Yong Teng's third sister married a Lim; her son is
  // Han Tiong Lim
  // --------------------------------------------------------------------------
  {
    id: "gan-granduncle-1",
    name: "顏文啟",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Gan Yong Teng's older brother — first of 顏貞錄's six children. Married 李金桃; their family — including the Sungai Petani and Penang households — is recorded on genealogy pages 21–22.",
    unknown: false,
  },
  {
    id: "gan-grandaunt",
    name: "顏文謹",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Gan Yong Teng's sister — third of 顏貞錄's six children (family recollection calls her the third sister). Married 林紀鴻; Han Tiong Lim's mother.",
    unknown: false,
  },
  {
    id: "gan-granduncle-4",
    name: "顏文喜",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Gan Yong Teng's younger brother — fourth of 顏貞錄's six children. The genealogy lists 章铨 (Simon) under him with the note 过房 (adopted across); further descendants unknown.",
    unknown: false,
  },
  {
    id: "gan-granduncle-5",
    name: "顏文經",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Gan Yong Teng's younger brother — fifth of 顏貞錄's six children. Married 陳珠娘; father of 顏章彩 and 顏章燕. His photo appears in the genealogy (page 23).",
    unknown: false,
  },
  {
    id: "gan-grandaunt-6",
    name: "顏文娥",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Gan Yong Teng's younger sister — sixth of 顏貞錄's six children. Married 丘金粦; their children carry the 丘 surname (page 23).",
    unknown: false,
  },
  {
    id: "lim-grandfather",
    name: "林紀鴻",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Han Tiong Lim's father; married 顏文謹, Gan Yong Teng's sister. Name from the genealogy (page 23).",
    unknown: false,
  },
  {
    id: "han-tiong-lim",
    name: "Han Tiong Lim",
    gender: "M",
    chineseName: "林漢忠",
    born: null, died: null,
    birthPlace: null, location: "Gig Harbor, Washington, USA", occupation: null,
    notes: "Son of 顏文謹 (Gan Yong Teng's sister) — first cousin of Cheong Koon's generation. 林汉忠 in the genealogy (page 23), which also records a sister, 林翠琴.",
    unknown: false,
  },
  {
    id: "irene-lim",
    name: "Irene Lim",
    gender: "F",
    chineseName: "陳玉娘",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Han Tiong Lim's wife; mother of Kevin, Kristen, and Travis. Mapped to 陳玉娘, the wife recorded in the genealogy (page 23) — please verify.",
    unknown: false,
  },
  {
    id: "kevin-lim",
    name: "Kevin Lim",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Oldest of Han Tiong and Irene's three children.",
    unknown: false,
  },
  {
    id: "kristen-lim",
    name: "Kristen Lim",
    gender: "F",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Middle child of Han Tiong and Irene.",
    unknown: false,
  },
  {
    id: "travis-lim",
    name: "Travis Lim",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: "Monroe, Washington, USA", occupation: null,
    notes: "Youngest of Han Tiong and Irene's three children.",
    unknown: false,
  },
  {
    id: "fiona",
    name: "Fiona",
    gender: "F",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Travis Lim's wife. Surname unknown.",
    unknown: false,
  },
  {
    id: "henry-lim",
    name: "Henry Lim",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Travis and Fiona's son.",
    unknown: false,
  },

  // --------------------------------------------------------------------------
  // Mom's side — great-grandparents
  // --------------------------------------------------------------------------
  {
    id: "gg-neoh-father",
    name: "Great-Grandfather Neoh",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Grandpa Neoh's father. Name and details unknown.",
    unknown: true,
  },
  {
    id: "gg-neoh-mother",
    name: "Great-Grandmother Neoh",
    gender: "F",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Grandpa Neoh's mother. Name and details unknown.",
    unknown: true,
  },
  {
    id: "gg-mgm-father",
    name: "Great-Grandfather (maternal grandmother's father)",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Father of Victor's maternal grandmother. Unknown.",
    unknown: true,
  },
  {
    id: "gg-mgm-mother",
    name: "Great-Grandmother (maternal grandmother's mother)",
    gender: "F",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Mother of Victor's maternal grandmother. Unknown.",
    unknown: true,
  },

  // --------------------------------------------------------------------------
  // Mom's side — grandparents
  // --------------------------------------------------------------------------
  {
    id: "grandpa-neoh",
    name: "Grandpa Neoh",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Victor's maternal grandfather (family name Neoh). Given name unknown.",
    unknown: true,
  },
  {
    id: "grandma-neoh",
    name: "Grandma Neoh",
    gender: "F",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Victor's maternal grandmother. Name unknown.",
    unknown: true,
  },

  // --------------------------------------------------------------------------
  // Mom's generation — Heng (oldest) and Cathy
  // --------------------------------------------------------------------------
  {
    id: "heng-neoh",
    name: "Heng Neoh",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Victor's uncle — Cathy's oldest brother.",
    unknown: false,
  },
  {
    id: "soo-neoh",
    name: "Soo Neoh",
    gender: "F",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Cathy's second youngest sister.",
    unknown: false,
  },
  {
    id: "cathy-gan",
    name: "Cathy Gan",
    gender: "F",
    chineseName: "梁素华",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Victor's mom (née Neoh — 梁 in the genealogy, Neoh in Hokkien).",
    unknown: false,
  },

  // --------------------------------------------------------------------------
  // Victor and siblings
  // --------------------------------------------------------------------------
  {
    id: "calvin-gan",
    name: "Calvin Gan",
    gender: "M",
    chineseName: "顏华冠",
    born: null, died: null,
    birthPlace: null, location: "Mississauga, Ontario, Canada", occupation: null,
    notes: null,
    unknown: false,
  },
  {
    id: "victor-gan",
    name: "Victor Gan",
    gender: "M",
    chineseName: "顏华胜",
    born: null, died: null,
    birthPlace: null, location: "Seattle, Washington, USA", occupation: null,
    notes: null,
    unknown: false,
  },
  {
    id: "christine-gan",
    name: "Christine Gan",
    gender: "F",
    chineseName: "顏婷梅",
    born: 1991, died: null,
    birthPlace: null,
    location: "Corner Brook, Newfoundland, Canada",
    occupation: null,
    notes: null,
    unknown: false,
  },
  {
    id: "ian-mcphee",
    name: "Ian McPhee",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: "Corner Brook, Newfoundland, Canada", occupation: null,
    notes: "Christine's husband.",
    unknown: false,
  },
  {
    id: "nolan-mcphee",
    name: "Nolan McPhee",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Christine and Ian's son — confirm surname.",
    unknown: false,
  },

  // --------------------------------------------------------------------------
  // Cousins (children of the Gan aunts and uncles) and their other parents
  // --------------------------------------------------------------------------
  {
    id: "erics-partner",
    name: "薛亚玉",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Eric Gan's wife; mother of Elaine and Serene. Name from the genealogy (page 22); English name unknown.",
    unknown: false,
  },
  {
    id: "serene-gan",
    name: "Serene Gan",
    gender: "F",
    chineseName: "顏婷君",
    born: null, died: null,
    birthPlace: null, location: "Kuala Lumpur, Malaysia", occupation: null,
    notes: "Victor's cousin — Eric's younger daughter.",
    unknown: false,
  },
  {
    id: "zhang-xueyu",
    name: "張學宇",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Serene's husband. Chinese name from the genealogy (page 22); English name unknown.",
    unknown: false,
  },
  {
    id: "elaine-gan",
    name: "Elaine Gan",
    gender: "F",
    chineseName: "顏婷俐",
    born: null, died: null,
    birthPlace: null, location: "Sydney, Australia", occupation: null,
    notes: "Victor's cousin — Eric's older daughter.",
    unknown: false,
  },
  {
    id: "douglas-maclaine-cross",
    name: "Douglas Lloyd Maclaine-Cross",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: "Sydney, Australia", occupation: null,
    notes: "Elaine's husband.",
    unknown: false,
  },
  {
    id: "laura-maclaine-cross",
    name: "Laura Li Hui Maclaine-Cross",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Elaine and Douglas's daughter, per the clan genealogy (page 22).",
    unknown: false,
  },
  {
    id: "sibling2-partner",
    name: "張惠桃",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏章池's wife; mother of Tinie, Michael, and James. Name from the genealogy (page 22).",
    unknown: false,
  },
  {
    id: "tinie-gan",
    name: "Tinie Gan",
    gender: "F",
    chineseName: "顏婷旎",
    born: null, died: null,
    birthPlace: null, location: "Melbourne, Australia", occupation: null,
    notes: "Victor's cousin — daughter of the 2nd-oldest Gan brother.",
    unknown: false,
  },
  {
    id: "zhou-qinglian",
    name: "周卿廉",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Tinie's husband per the clan genealogy (page 22) — please confirm.",
    unknown: false,
  },
  {
    id: "zhou-yijun",
    name: "周毅俊",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Tinie and 周卿廉's son, per the clan genealogy (page 22).",
    unknown: false,
  },
  {
    id: "zhou-yijuan",
    name: "周怡娟",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Tinie and 周卿廉's daughter, per the clan genealogy (page 22).",
    unknown: false,
  },
  {
    id: "michael-gan",
    name: "Michael Gan",
    gender: "M",
    chineseName: "顏華昀",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Victor's cousin — youngest child of the 2nd-oldest Gan brother.",
    unknown: false,
  },
  {
    id: "gan-suyan",
    name: "甘素嫣",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "James's wife per the clan genealogy (page 22) — please confirm.",
    unknown: false,
  },
  {
    id: "yan-jiemin",
    name: "顏洁敏",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "James and 甘素嫣's daughter, per the clan genealogy (page 22).",
    unknown: false,
  },
  {
    id: "m-gan",
    name: "James Gan",
    gender: "M",
    chineseName: "顏华琸",
    born: null, died: null,
    birthPlace: null, location: "Singapore", occupation: null,
    notes: "Victor's cousin — second child of the 2nd-oldest Gan brother. Chinese-name character 琸 hard to read in the genealogy scan — please verify.",
    unknown: false,
  },
  {
    id: "zheng-ziyi",
    name: "郑紫意",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Michael's wife per the clan genealogy (page 22) — please confirm.",
    unknown: false,
  },
  {
    id: "yan-aimin",
    name: "顏艾敏",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Michael and 郑紫意's daughter, per the clan genealogy (page 22).",
    unknown: false,
  },
  {
    id: "yan-guofeng",
    name: "顏国沣",
    gender: "M",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Michael and 郑紫意's son, per the clan genealogy (page 22).",
    unknown: false,
  },
  {
    id: "sibling3-partner",
    name: "陳玉霞",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "顏章炫's wife; mother of Tivien and Alex. Name from the genealogy (page 22); English name unknown.",
    unknown: false,
  },
  {
    id: "tivien-gan",
    name: "Tivien Gan",
    gender: "F",
    chineseName: "顏婷瑋",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Victor's cousin — the 4th-oldest Gan brother's daughter, Alex's older sister.",
    unknown: false,
  },
  {
    id: "sibling3-son",
    name: "Alex Gan",
    gender: "M",
    chineseName: "顏華坊",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Victor's cousin — the 4th-oldest Gan brother's son, Tivien's younger brother.",
    unknown: false,
  },
  {
    id: "simons-partner",
    name: "邝芝雯",
    gender: "F",
    chineseName: null,
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Jonathan's mother; she and Simon Gan are divorced. Name from the genealogy (page 22); English name unknown.",
    unknown: false,
  },
  {
    id: "jonathan-gan",
    name: "Jonathan Gan",
    gender: "M",
    chineseName: "顏华安",
    born: null, died: null,
    birthPlace: null, location: "Hilversum, Netherlands", occupation: null,
    notes: "Victor's cousin — Simon's son.",
    unknown: false,
  },
  {
    id: "jacquelines-partner",
    name: "Alun",
    gender: "M",
    chineseName: "張少倫",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Jacqueline Gan's husband, Maria's father — 張少倫 in the genealogy (page 22).",
    unknown: false,
  },
  {
    id: "maria",
    name: "Maria",
    gender: "F",
    chineseName: "張玉瑤",
    born: null, died: null,
    birthPlace: null, location: "Utrecht, Netherlands", occupation: null,
    notes: "Victor's cousin — Jacqueline's daughter. 張玉瑤 in the genealogy (page 22), so her surname is 張.",
    unknown: false,
  },
  {
    id: "erik",
    name: "Erik",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Maria's husband. Surname unknown.",
    unknown: false,
  },
  {
    id: "jayden",
    name: "Jayden",
    gender: "M",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Maria and Erik's son. Surname unknown.",
    unknown: false,
  },
  {
    id: "johns-partner",
    name: "Diane Gan",
    gender: "F",
    chineseName: "李美英",
    born: null, died: null,
    birthPlace: null, location: null, occupation: null,
    notes: "Mother of Natalie and Stephanie; she and John Gan are divorced. 李美英 in the genealogy (page 22), so her maiden surname is 李.",
    unknown: false,
  },
  {
    id: "natalie-gan",
    name: "Natalie Gan",
    gender: "F",
    chineseName: "顏婷玗",
    born: null, died: null,
    birthPlace: null, location: "Vancouver, British Columbia, Canada", occupation: null,
    notes: "Victor's cousin — John's younger daughter. Mapped to 婷玗 in the genealogy on birth-order grounds — please verify.",
    unknown: false,
  },
  {
    id: "stephanie-gan",
    name: "Stephanie Gan",
    gender: "F",
    chineseName: "顏婷妍",
    born: null, died: null,
    birthPlace: null, location: "Ottawa, Ontario, Canada", occupation: null,
    notes: "Victor's cousin — John's older daughter. Mapped to 婷妍 in the genealogy on birth-order grounds — please verify.",
    unknown: false,
  },
];

const UNIONS = [
  // Patriline above the great-grandparents (wives not yet transcribed)
  { id: "u-gan-30",   partners: ["gan-30-hengxiao", "gan-30-hengxiao-wife"], status: "married", start: null, end: null, children: ["gan-31-lipan"] },
  { id: "u-gan-31",   partners: ["gan-31-lipan", "gan-31-lipan-wife"],       status: "married", start: null, end: null,
    children: ["yan-zhengai", "yan-zhenzan", "yan-zhenli", "gg-gan-father", "yan-zhenreng"] },

  // Great-grandparents → grandparents (顏貞錄's six children, genealogy order)
  { id: "u-gg-gan",   partners: ["gg-gan-father", "gg-gan-mother"],   status: "married", start: null, end: null,
    children: ["gan-granduncle-1", "grandpa-gan", "gan-grandaunt", "gan-granduncle-4", "gan-granduncle-5", "gan-grandaunt-6"] },
  { id: "u-gg-neoh",  partners: ["gg-neoh-father", "gg-neoh-mother"], status: "married", start: null, end: null, children: ["grandpa-neoh"] },
  { id: "u-gg-mgm",   partners: ["gg-mgm-father", "gg-mgm-mother"],   status: "married", start: null, end: null, children: ["grandma-neoh"] },

  // Grandparents → parents' generation (children listed in birth order)
  { id: "u-gan-gp",   partners: ["grandpa-gan", "grandma-gan"],       status: "married", start: null, end: null,
    children: ["forest-gan", "gan-sibling-2", "simon-gan", "gan-sibling-3", "cheong-koon-gan", "eric-gan", "john-gan", "jacqueline-gan"] },
  { id: "u-neoh",     partners: ["grandpa-neoh", "grandma-neoh"],     status: "married", start: null, end: null,
    children: ["heng-neoh", "soo-neoh", "cathy-gan"] },

  // Parents → Victor's generation
  { id: "u-cheong-cathy", partners: ["cheong-koon-gan", "cathy-gan"], status: "married", start: null, end: null,
    children: ["calvin-gan", "victor-gan", "christine-gan"] },

  // Christine + Ian
  { id: "u-christine-ian", partners: ["christine-gan", "ian-mcphee"], status: "married", start: null, end: null,
    children: ["nolan-mcphee"] },

  // Aunts/uncles → cousins (spouse names still unknown)
  { id: "u-eric",       partners: ["eric-gan", "erics-partner"],             status: "married", start: null, end: null,
    children: ["elaine-gan", "serene-gan"] },
  { id: "u-elaine-douglas", partners: ["elaine-gan", "douglas-maclaine-cross"], status: "married", start: null, end: null,
    children: ["laura-maclaine-cross"] },
  { id: "u-sibling2",   partners: ["gan-sibling-2", "sibling2-partner"],     status: "married", start: null, end: null,
    children: ["tinie-gan", "m-gan", "michael-gan"] },

  // Cousins' own families, from the genealogy (page 22) — confirm details
  { id: "u-serene",  partners: ["serene-gan", "zhang-xueyu"],  status: "married", start: null, end: null, children: [] },
  { id: "u-tinie",   partners: ["tinie-gan", "zhou-qinglian"], status: "married", start: null, end: null,
    children: ["zhou-yijun", "zhou-yijuan"] },
  { id: "u-james",   partners: ["m-gan", "gan-suyan"],         status: "married", start: null, end: null,
    children: ["yan-jiemin"] },
  { id: "u-michael", partners: ["michael-gan", "zheng-ziyi"],  status: "married", start: null, end: null,
    children: ["yan-aimin", "yan-guofeng"] },
  { id: "u-sibling3",   partners: ["gan-sibling-3", "sibling3-partner"],     status: "married", start: null, end: null,
    children: ["tivien-gan", "sibling3-son"] },

  // 文啟's branch (pages 21–22)
  { id: "u-wenqi",      partners: ["gan-granduncle-1", "li-jintao"],   status: "married", start: null, end: null,
    children: ["yan-zhangyi", "yan-zhangxiang", "yan-zhangyao", "yan-suzhu", "yan-suling"] },
  { id: "u-zhangyi",    partners: ["yan-zhangyi", "chen-yue-e"],       status: "married", start: null, end: null,
    children: ["yan-huaen", "yan-tingjuan", "yan-huaqun"] },
  { id: "u-huaen",      partners: ["yan-huaen", "guo-fuyi"],           status: "married", start: null, end: null,
    children: ["yan-yuxiang", "yan-xinyue"] },
  { id: "u-tingjuan",   partners: ["yan-tingjuan", "feng-jihao"],      status: "married", start: null, end: null,
    children: ["feng-yuheng", "feng-ruiheng"] },
  { id: "u-huaqun",     partners: ["yan-huaqun", "du-jincong"],        status: "married", start: null, end: null, children: [] },
  { id: "u-zhangxiang", partners: ["yan-zhangxiang", "li-suping"],     status: "married", start: null, end: null,
    children: ["yan-huazhao", "yan-huahan", "yan-huawei"] },
  { id: "u-huazhao",    partners: ["yan-huazhao", "chen-siyi"],        status: "married", start: null, end: null,
    children: ["yan-yurui", "yan-yuhui"] },
  { id: "u-huahan",     partners: ["yan-huahan", "huang-meimei"],      status: "married", start: null, end: null,
    children: ["yan-yujun36"] },
  { id: "u-huawei",     partners: ["yan-huawei", "wang-xiuqing"],      status: "married", start: null, end: null,
    children: ["yan-yuxin", "yan-yuyi"] },
  { id: "u-zhangyao",   partners: ["yan-zhangyao", "li-yaxiang"],      status: "married", start: null, end: null, children: [] },
  { id: "u-suling",     partners: ["yan-suling", "peng-guoying"],      status: "married", start: null, end: null, children: [] },

  // 文經's and 文娥's families (page 23)
  { id: "u-wenjing",    partners: ["gan-granduncle-5", "chen-zhuniang"], status: "married", start: null, end: null,
    children: ["yan-zhangcai", "yan-zhangyan"] },
  { id: "u-zhangcai",   partners: ["yan-zhangcai", "lin-wenquan"],     status: "married", start: null, end: null,
    children: ["lin-shutong"] },
  { id: "u-zhangyan",   partners: ["yan-zhangyan", "wang-shian"],      status: "married", start: null, end: null,
    children: ["wang-jinchuan", "wang-jingfen", "wang-jingling"] },
  { id: "u-wene",       partners: ["gan-grandaunt-6", "qiu-jinlin"],   status: "married", start: null, end: null,
    children: ["qiu-cuiyue", "qiu-zhuangming", "qiu-zhuangrong", "qiu-zhuangwei"] },
  { id: "u-cuiqin",     partners: ["lin-cuiqin", "lan-quanrui"],       status: "married", start: null, end: null,
    children: ["lan-renli"] },

  // Lim branch
  { id: "u-lim-gp",       partners: ["lim-grandfather", "gan-grandaunt"], status: "married", start: null, end: null,
    children: ["han-tiong-lim", "lin-cuiqin"] },
  { id: "u-han-irene",    partners: ["han-tiong-lim", "irene-lim"],       status: "married", start: null, end: null,
    children: ["kevin-lim", "kristen-lim", "travis-lim"] },
  { id: "u-travis-fiona", partners: ["travis-lim", "fiona"],              status: "married", start: null, end: null,
    children: ["henry-lim"] },
  { id: "u-simon",      partners: ["simon-gan", "simons-partner"],           status: "divorced", start: null, end: null,
    children: ["jonathan-gan"] },
  { id: "u-jacqueline", partners: ["jacqueline-gan", "jacquelines-partner"], status: "married", start: null, end: null,
    children: ["maria"] },
  { id: "u-maria-erik", partners: ["maria", "erik"],                         status: "married", start: null, end: null,
    children: ["jayden"] },
  { id: "u-john",       partners: ["john-gan", "johns-partner"],             status: "divorced", start: null, end: null,
    children: ["stephanie-gan", "natalie-gan"] },
];

// The person shown when the site first loads.
const HOME_PERSON = "grandpa-gan";

// Default roots for the Full tree view — the generations in living memory.
// The complete clan tree (from the 30th generation) lives at #/tree/all.
const TREE_ROOTS = ["grandpa-gan", "gan-grandaunt", "grandpa-neoh"];
